/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.assistencia.visao;

import javax.swing.JFrame;

/**
 *
 * @author ramon
 */
public class OpcoesLocalizar extends javax.swing.JFrame {

    /**
     * Creates new form OpcoesLocalizar
     */
    public OpcoesLocalizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLocalizaFuncionario = new javax.swing.JButton();
        jButtonLocalizaCliente = new javax.swing.JButton();
        jButtonLocalizaMarca = new javax.swing.JButton();
        jButtonLocalizaModelo = new javax.swing.JButton();
        jButtonLocalizaOrdem = new javax.swing.JButton();
        jButtonLocalizaPeca = new javax.swing.JButton();
        jButtonLocalizaProduto = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonLocalizaFuncionario.setText("Funcionário");
        jButtonLocalizaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizaFuncionarioActionPerformed(evt);
            }
        });

        jButtonLocalizaCliente.setText("Cliente");
        jButtonLocalizaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizaClienteActionPerformed(evt);
            }
        });

        jButtonLocalizaMarca.setText("Marca");
        jButtonLocalizaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizaMarcaActionPerformed(evt);
            }
        });

        jButtonLocalizaModelo.setText("Modelo");
        jButtonLocalizaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizaModeloActionPerformed(evt);
            }
        });

        jButtonLocalizaOrdem.setText("Ordem");
        jButtonLocalizaOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizaOrdemActionPerformed(evt);
            }
        });

        jButtonLocalizaPeca.setText("Peça");
        jButtonLocalizaPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizaPecaActionPerformed(evt);
            }
        });

        jButtonLocalizaProduto.setText("Produto");
        jButtonLocalizaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizaProdutoActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonLocalizaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLocalizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLocalizaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLocalizaModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLocalizaOrdem))
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLocalizaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLocalizaProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonLocalizaCliente, jButtonLocalizaFuncionario, jButtonLocalizaMarca, jButtonLocalizaModelo, jButtonLocalizaOrdem, jButtonLocalizaPeca, jButtonLocalizaProduto});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonLocalizaOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLocalizaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLocalizaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLocalizaPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLocalizaProduto)))
                    .addComponent(jButtonLocalizaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLocalizaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonFechar, jButtonLocalizaCliente, jButtonLocalizaFuncionario, jButtonLocalizaMarca, jButtonLocalizaModelo, jButtonLocalizaOrdem, jButtonLocalizaPeca, jButtonLocalizaProduto});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonLocalizaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizaFuncionarioActionPerformed
        // TODO add your handling code here:
        
        TelaLocalizarFuncionario tela = new TelaLocalizarFuncionario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLocalizaFuncionarioActionPerformed

    private void jButtonLocalizaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizaClienteActionPerformed
        // TODO add your handling code here:
         TelaLocalizarCliente tela = new TelaLocalizarCliente();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLocalizaClienteActionPerformed

    private void jButtonLocalizaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizaMarcaActionPerformed
        // TODO add your handling code here:
        TelaCadastroMarca tela = new TelaCadastroMarca();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLocalizaMarcaActionPerformed

    private void jButtonLocalizaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizaModeloActionPerformed
        // TODO add your handling code here:
         TelaCadastroModelo tela = new TelaCadastroModelo();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLocalizaModeloActionPerformed

    private void jButtonLocalizaOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizaOrdemActionPerformed
        // TODO add your handling code here:
         TelaCadastroOrdem tela = new TelaCadastroOrdem();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLocalizaOrdemActionPerformed

    private void jButtonLocalizaPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizaPecaActionPerformed
        // TODO add your handling code here:
         TelaCadastroPeca tela = new TelaCadastroPeca();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLocalizaPecaActionPerformed

    private void jButtonLocalizaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizaProdutoActionPerformed
        // TODO add your handling code here:
         TelaCadastroProduto tela = new TelaCadastroProduto();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonLocalizaProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcoesLocalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcoesLocalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcoesLocalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcoesLocalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcoesLocalizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLocalizaCliente;
    private javax.swing.JButton jButtonLocalizaFuncionario;
    private javax.swing.JButton jButtonLocalizaMarca;
    private javax.swing.JButton jButtonLocalizaModelo;
    private javax.swing.JButton jButtonLocalizaOrdem;
    private javax.swing.JButton jButtonLocalizaPeca;
    private javax.swing.JButton jButtonLocalizaProduto;
    // End of variables declaration//GEN-END:variables
}
