/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsul.assistencia.visao;

/**
 *
 * @author ramon
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCad = new javax.swing.JMenu();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItemCadProduto = new javax.swing.JMenuItem();
        jMenuItemCadOrdem = new javax.swing.JMenuItem();
        jMenuOrc = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuLoc = new javax.swing.JMenu();
        jMenuItemLocalizarCliente = new javax.swing.JMenuItem();
        jMenuItemLocalizarFuncionario = new javax.swing.JMenuItem();
        jMenuItemLocalizarOrdem = new javax.swing.JMenuItem();
        jMenuItemLocalizarOrçamento = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifsul/assistencia/imagens/fundo2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jMenuCad.setText("Cadastros");

        jMenuItemCadCliente.setText("Clientes");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuItemCadCliente);

        jMenuItemFuncionario.setText("Fucionarios");
        jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuItemFuncionario);

        jMenuItemCadProduto.setText("Produtos");
        jMenuItemCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadProdutoActionPerformed(evt);
            }
        });
        jMenuCad.add(jMenuItemCadProduto);

        jMenuItemCadOrdem.setText("Ordens");
        jMenuCad.add(jMenuItemCadOrdem);

        jMenuBar1.add(jMenuCad);

        jMenuOrc.setText("Orcamento");

        jMenuItem1.setText("jMenuItem1");
        jMenuOrc.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenuOrc.add(jMenuItem2);

        jMenuBar1.add(jMenuOrc);

        jMenuLoc.setText("Localizar");

        jMenuItemLocalizarCliente.setText("Cliente");
        jMenuLoc.add(jMenuItemLocalizarCliente);

        jMenuItemLocalizarFuncionario.setText("Funcionario");
        jMenuLoc.add(jMenuItemLocalizarFuncionario);

        jMenuItemLocalizarOrdem.setText("Ordem");
        jMenuLoc.add(jMenuItemLocalizarOrdem);

        jMenuItemLocalizarOrçamento.setText("Orçamento");
        jMenuLoc.add(jMenuItemLocalizarOrçamento);

        jMenuBar1.add(jMenuLoc);

        jMenu3.setText("Ajuda");

        jMenuItem7.setText("Sobre");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 363, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(732, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        // TODO add your handling code here:
        TelaCadastroCliente tela = new TelaCadastroCliente();
        tela.setVisible(true);
       // dispose();
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jMenuItemCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadProdutoActionPerformed

    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
        // TODO add your handling code here:
        TelaCadastroFuncionario tela = new TelaCadastroFuncionario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCad;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadOrdem;
    private javax.swing.JMenuItem jMenuItemCadProduto;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemLocalizarCliente;
    private javax.swing.JMenuItem jMenuItemLocalizarFuncionario;
    private javax.swing.JMenuItem jMenuItemLocalizarOrdem;
    private javax.swing.JMenuItem jMenuItemLocalizarOrçamento;
    private javax.swing.JMenu jMenuLoc;
    private javax.swing.JMenu jMenuOrc;
    // End of variables declaration//GEN-END:variables
}
